name: Build CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        config: ['debug', 'release']
        compiler: ['cl', 'clang', 'gcc']
        platform: ['x64']
        exclude:
          - os: ubuntu-20.04
            compiler: cl
          - os: macos-latest
            compiler: cl
      fail-fast: false
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
          fetch-depth: '0'
      - name: Setup
        uses: ./.github/actions/common-setup
        with:
          os: ${{matrix.os}}
          compiler: ${{matrix.compiler}}
          platform: ${{matrix.platform}}
          config: ${{matrix.config}}
      - run: cmake --workflow --preset "${{matrix.config}}-dist"
      - uses: actions/upload-artifact@v3
        with:
          name: slang-build-${{matrix.os}}-${{matrix.platform}}-${{matrix.compiler}}-${{matrix.config}}
          path: build/dist-${{matrix.config}}/**/slang/*
