name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        compiler: ['gcc', 'clang', 'cl']
        config: ['debug', 'release']
        platform: ['x64']
        exclude:
          # Exclude invalid or undesired os/compiler
          - { os: ubuntu-20.04, compiler: cl }
          - { os: macos-latest, compiler: cl }
          - { os: macos-latest, compiler: gcc }
          - { os: windows-latest, compiler: gcc }
          - { os: windows-latest, compiler: clang }
          # or os/config combinations
          - { os: macos-latest, config: debug }
        include:
          # Set a test category depending on the config, smoke by default,
          # quick or full conditionally otherwise
          - test-category: smoke
          - { os: windows-latest, test-category: quick }
          - { config: release, test-category: full }
          # Only CL has werror
          - warnings-as-errors: false
          - { compiler: cl, warnings-as-errors: true }
      fail-fast: false
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
      - &checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          fetch-depth: '0'
      - &setup
        name: Setup
        uses: ./.github/actions/common-setup
        with:
          os: ${{matrix.os}}
          compiler: ${{matrix.compiler}}
          platform: ${{matrix.platform}}
          config: ${{matrix.config}}
      - &build
        name: Build Slang
        run: |
          if [[ "${{ matrix.os }}" =~ "windows" && "${{ matrix.config }}" != "release" ]]; then
            # Doing a debug build will try to link against a release built llvm, this
            # is a problem on Windows, so make slang-llvm in release build and use
            # that as though it's a fetched binary via these presets.
            cmake --workflow --preset slang-llvm
            # Configure, pointing to our just-generated slang-llvm archive
            cmake --preset default --fresh \
              -DSLANG_SLANG_LLVM_FLAVOR=FETCH_BINARY \
              -DSLANG_SLANG_LLVM_BINARY_URL=$(pwd)/build/dist-release/slang-slang-llvm.zip \
              -DCMAKE_COMPILE_WARNING_AS_ERROR=${{matrix.warnings-as-errors}}
            cmake --workflow --preset "${{matrix.config}}"
          else
            # Otherwise, use the system llvm we have just build or got from the
            # cache in the setup phase
            cmake --preset default --fresh \
              -DSLANG_SLANG_LLVM_FLAVOR=USE_SYSTEM_LLVM \
              -DCMAKE_COMPILE_WARNING_AS_ERROR=${{matrix.warnings-as-errors}}
            cmake --workflow --preset "${{matrix.config}}"
          fi
      - &test
        name: Test Slang
        run: |
          export SLANG_RUN_SPIRV_VALIDATION=1
          $bin_dir/slang-test \
            -use-test-server \
            -api all-dx12 \
            -category ${{ matrix.test-category }} \
            -expected-failure-list tests/expected-failure-github.txt
      - &upload
        uses: actions/upload-artifact@v3
        with:
          name: slang-build-${{matrix.os}}-${{matrix.platform}}-${{matrix.compiler}}-${{matrix.config}}
          # The install directory used in the packaging step
          path: build/dist-${{matrix.config}}/**/slang/*

  aarch64-build:
    runs-on: [self-hosted, Linux, ARM64]
    strategy:
      matrix:
        include:
          - os: ubuntu
            compiler: gcc
            platform: aarch64
            config: release
            warnings-as-errors: false
            test-category: smoke
    timeout-minutes: 100
    defaults:
      run:
        shell: bash
    steps:
      - *checkout
      - *setup
      - *build
      - *test
      - *upload

  full-gpu-tests:
    runs-on: [Windows, self-hosted]
    strategy:
      matrix:
        include:
          - os: windows-latest
            compiler: cl
            platform: x64
            config: release
            warnings-as-errors: false
            test-category: full
    defaults:
      run:
        shell: bash
    timeout-minutes: 100
    steps:
      - *checkout
      - *setup
      - *build
      - name: Test SPIR-V Direct
        id: spirv
        run: |
          export SLANG_RUN_SPIRV_VALIDATION=1
          $bin_dir/slang-test \
            -use-test-server \
            -server-count 8 \
            -emit-spirv-directly \
            -api vk \
            -category ${{ matrix.test-category }} \
            -expected-failure-list tests/expected-failure.txt
      - name: Test
        # Run even if the previous step fails
        if: success() || steps.spirv.conclusion == 'failure'
        run: |
          $bin_dir/slang-test \
            -use-test-server \
            -server-count 8 \
            -category ${{ matrix.test-category }} \
            -api all-cpu
